package com.athmarine.entity;

public enum ServiceRequestStatus {

	NEW_REQUEST, BIDS_RECEIVED, PO_ISSUED, PO_ACCEPTED, WORK_IN_PROGRESS, INVOICE_RECEIVED, INVOICE_PAID, REJECT,
	COMPLETED, APPROVER_PENDING, PO_RAISED, INVOICE_RAISED, BIDS_IN_PROGRESS, INTERESTED, BID_RAISED, TIMED_OUT,
	PO_DECLINED, NOT_INTERESTED, WITHDRAWN, ENGINEER_APPROVAL_PENDING, NOT_RAISED, RAISED, RECEIVED , APPROVED, DECLINED, REVOKED,
	PENDING, HOC_APPROVAL_PENDING
}
